import { PublishError } from '../shared/errors.mjs';
import {
  assertMergeReady,
  evaluateRequiredChecks,
  isMergeReadinessPending,
} from './validation.mjs';

export function safeBranchName(message, { prefix = 'change', now = new Date() } = {}) {
  const stem =
    message
      .toLowerCase()
      .replace(/[^a-z0-9._-]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 48)
      .replace(/-+$/g, '') || 'local-change';
  const timestamp = now
    .toISOString()
    .replace(/[-:]/g, '')
    .replace('T', '-')
    .slice(0, 15);
  return `${prefix}/${stem}-${timestamp}`;
}

export function publishRecord({ classification, validation, headSha, defaultBranch }) {
  return [
    '## Publish record',
    '',
    `- Classification: \`${classification.toUpperCase()}\``,
    `- Validation: ${validation}`,
    `- Head commit: \`${headSha}\``,
    `- Target branch: \`${defaultBranch}\``,
    '',
    'Generated by `publish-changes.mjs`.',
  ].join('\n');
}

export function prOnlyPublishRecord({ headSha, defaultBranch }) {
  return [
    '## Publish record',
    '',
    '- Mode: `PR_ONLY`',
    `- Head commit: \`${headSha}\``,
    `- Target branch: \`${defaultBranch}\``,
    '',
    'Generated by `publish-changes.mjs`.',
  ].join('\n');
}

export async function ensureFeatureBranch({
  state,
  git,
  prompts,
  output,
  commitMessage,
  classification,
  branchPrefix,
}) {
  if (!['main', 'master', state.defaultBranch].includes(state.branch)) return state.branch;
  const branch = safeBranchName(commitMessage, { prefix: branchPrefix });
  output.warning(`Direct publishing from ${state.branch} is blocked. Feature branch: ${branch}`);
  if (classification !== 'small_safe' && !(await prompts.confirm(`Create and switch to ${branch}?`))) {
    throw new PublishError('USER_CANCELLED', 'Feature branch creation was not approved.');
  }
  await git.switchCreate(branch);
  return branch;
}

export async function createOrUpdatePullRequest({
  gh,
  git,
  repo,
  branch,
  defaultBranch,
  title,
  classification,
  validation,
}) {
  const headSha = await git.head();
  const body = publishRecord({ classification, validation, headSha, defaultBranch });
  const existing = await gh.listPullRequests(repo, [
    '--state',
    'open',
    '--head',
    branch,
    '--limit',
    '1',
  ]);
  if (existing[0]) {
    await gh.commentPullRequest(repo, existing[0].number, body);
    return {
      pr: await gh.viewPullRequest(repo, existing[0].number),
      action: 'updated',
    };
  }
  await gh.createPullRequest(repo, { base: defaultBranch, head: branch, title, body });
  return {
    pr: await gh.viewPullRequest(repo, branch),
    action: 'created',
  };
}

export async function verifyAndMerge({
  gh,
  git,
  repo,
  pr,
  branch,
  defaultBranch,
  mode,
  output,
  expectedHeadSha = '',
  attempts = 6,
  intervalMs = 2000,
  sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms)),
}) {
  const headSha = expectedHeadSha || (await git.head());
  let fresh;
  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    fresh = await gh.viewPullRequest(repo, pr.number);
    if (!isMergeReadinessPending(fresh)) break;
    if (attempt === 1) {
      output?.warning(
        `GitHub is still calculating merge readiness for PR #${pr.number}; waiting before merge verification.`,
      );
    }
    if (attempt < attempts) await sleep(intervalMs);
  }
  assertMergeReady(fresh, { branch, defaultBranch, headSha });
  const checks = await gh.requiredChecks(repo, fresh.number);
  const checkState = evaluateRequiredChecks(checks, mode);
  await gh.merge(repo, fresh.number, { auto: mode === 'auto', headSha });
  return { pr: fresh, checkState };
}

export async function pollForVerifiedMerge({
  gh,
  repo,
  prNumber,
  defaultBranch,
  attempts = 12,
  intervalMs = 5000,
  sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms)),
}) {
  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    const pr = await gh.viewPullRequest(repo, prNumber);
    if (pr.mergedAt && pr.baseRefName === defaultBranch) return pr;
    if (pr.state !== 'OPEN') {
      throw new PublishError(
        'POLICY_BLOCKED',
        `PR #${pr.number} is ${pr.state} without verified merge into ${defaultBranch}.`,
      );
    }
    if (attempt < attempts) await sleep(intervalMs);
  }
  throw new PublishError(
    'CHECKS_PENDING',
    `PR #${prNumber} was not verified merged after ${attempts} checks.`,
  );
}

export async function refreshDefaultBranch({
  git,
  prompts,
  output,
  defaultBranch,
  verifiedPr,
  fastForwardOnly = false,
}) {
  if (!verifiedPr.mergedAt || verifiedPr.baseRefName !== defaultBranch) {
    throw new PublishError(
      'POLICY_BLOCKED',
      `PR #${verifiedPr.number} is not verified merged into ${defaultBranch}.`,
    );
  }
  if (await git.status()) {
    throw new PublishError('UNSAFE_BRANCH_STATE', 'Worktree must be clean before branch refresh.');
  }

  await git.fetchDefault(defaultBranch);
  await git.switchBranch(defaultBranch);
  const remoteRef = `origin/${defaultBranch}`;
  if (await git.canFastForwardTo(remoteRef)) {
    await git.pullFastForward(defaultBranch);
    output.success(`Refreshed ${defaultBranch} with fast-forward only.`);
    return { refreshed: true, reset: false };
  }

  if (fastForwardOnly) {
    output.skipped(
      `Local ${defaultBranch} cannot fast-forward to ${remoteRef}; history was left intact.`,
    );
    return { refreshed: false, reset: false, reason: 'non-fast-forward' };
  }

  const backup = `backup/${defaultBranch}-before-reset-${Date.now()}`;
  await git.createBackup(backup);
  output.danger(`Local ${defaultBranch} diverged. Backup created: ${backup}`);
  const approved = await prompts.typed(
    `Reset local ${defaultBranch} to ${remoteRef}? Backup ${backup} will be preserved.`,
    'RESET_MAIN_TO_ORIGIN',
  );
  if (!approved) {
    output.skipped(`Reset not approved. Backup preserved: ${backup}`);
    return { refreshed: false, reset: false, backup };
  }
  await git.resetHard(remoteRef);
  output.success(`Reset ${defaultBranch} to ${remoteRef}.`);
  return { refreshed: true, reset: true, backup };
}
